# Generated by Django 2.2.6 on 2019-12-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
